// <auto-generated />
using System;
using ElGuayabot.Persistence.Implementation.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace ElGuayabot.Persistence.Implementation.Migrations
{
    [DbContext(typeof(ElGuayabotDbContext))]
    [Migration("20190920140104_ChangedConversationsName")]
    partial class ChangedConversationsName
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("ElGuayabot.Domain.Entity.Chat", b =>
                {
                    b.Property<long>("Id");

                    b.Property<DateTime>("FirstSeen");

                    b.Property<string>("Title");

                    b.Property<int>("Type");

                    b.Property<string>("Username");

                    b.HasKey("Id");

                    b.ToTable("Chats");
                });

            modelBuilder.Entity("ElGuayabot.Domain.Entity.Conversation", b =>
                {
                    b.Property<long>("ChatId");

                    b.Property<int>("UserId");

                    b.HasKey("ChatId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("Conversations");
                });

            modelBuilder.Entity("ElGuayabot.Domain.Entity.User", b =>
                {
                    b.Property<int>("Id");

                    b.Property<DateTime>("FirstSeen");

                    b.Property<bool>("IsAdmin");

                    b.Property<bool>("IsBot");

                    b.Property<string>("LanguageCode");

                    b.Property<string>("Username");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ElGuayabot.Domain.Entity.Conversation", b =>
                {
                    b.HasOne("ElGuayabot.Domain.Entity.Chat", "Chat")
                        .WithMany("Conversations")
                        .HasForeignKey("ChatId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ElGuayabot.Domain.Entity.User", "User")
                        .WithMany("Conversations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
